### ISSUE TITLE
Installs only with very many package dependency warnings, then does not find any flow errors

### ISSUE THREAD

**Issue by alan-birchenough** [Flow-Scanner/lightning-flow-scanner#76]
This was working fine last week.  I just updated to SFDX version 7, and I am on NodeJS version v18.17.1 and NPM version 9.6.7.  (I plan to upgrade to `sf` version 2, but haven't gotten around to it yet.)

I reinstalled this plugin, since somewhere along the line it seemed to have gotten "lost" so it no longer showed up in the sfdx plugins list.  I saw the following errors and warnings:
sfdx plugins:install lightning-flow-scanner 
**? This plugin is not digitally signed and its authenticity cannot be verified. Continue installation?** Yes
Because you approved this plugin, you can avoid future installation confirmations by adding the plugin to the unsignedPluginAllowList.json file. For details, see https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_allowlist.htm.
Finished digital signature check.
Installing plugin lightning-flow-scanner... ⣾ [1/4] Resolving packages...
Installing plugin lightning-flow-scanner... ⣽ [1/4] Resolving packages...
warning lightning-flow-scanner > @oclif/config@1.18.17: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
Installing plugin lightning-flow-scanner... ⣻ [1/4] Resolving packages...
warning lightning-flow-scanner > @oclif/errors@1.3.6: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning lightning-flow-scanner > @oclif/command > @oclif/errors@1.3.6: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning lightning-flow-scanner > @oclif/config > @oclif/errors@1.3.6: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning lightning-flow-scanner > @salesforce/command@2.2.0: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning lightning-flow-scanner > @salesforce/command > @oclif/command@1.8.36: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
Installing plugin lightning-flow-scanner... ⣯ [1/4] Resolving packages...
warning lightning-flow-scanner > @salesforce/command > @oclif/plugin-help > @oclif/command@1.8.36: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning lightning-flow-scanner > @oclif/command > @oclif/help@1.0.15: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning lightning-flow-scanner > @oclif/command > @oclif/help > @oclif/config@1.18.16: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning lightning-flow-scanner > @oclif/command > @oclif/help > @oclif/errors@1.3.6: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning lightning-flow-scanner > @oclif/command > @oclif/help > @oclif/config > @oclif/errors@1.3.6: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning lightning-flow-scanner > @salesforce/command > cli-ux@4.9.3: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
Installing plugin lightning-flow-scanner... ⣷ [1/4] Resolving packages...
warning lightning-flow-scanner > @oclif/command > @oclif/parser@3.8.17: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning lightning-flow-scanner > @oclif/config > @oclif/parser@3.8.17: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning lightning-flow-scanner > @salesforce/command > @oclif/parser@3.8.17: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning lightning-flow-scanner > @oclif/command > @oclif/help > @oclif/config > @oclif/parser@3.8.17: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
Installing plugin lightning-flow-scanner... ⢿ [1/4] Resolving packages...
Installing plugin lightning-flow-scanner... ⣽ [1/4] Resolving packages...
warning lightning-flow-scanner > @salesforce/core > jsforce > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
Installing plugin lightning-flow-scanner... ⣾ [1/4] Resolving packages...
Installing plugin lightning-flow-scanner... ⣽ [1/4] Resolving packages...
Installing plugin lightning-flow-scanner... installed v2.12.0

Thinking this might just be the usual whining from NPM, I went ahead and tried checking some flows.  No matter whether I ran
`sfdx flow:scan -u <user-name>` or `sfdx flow:scan -d <directory-containing-flow-files>` the scanner would just come back saying it found `n` flows, but no errors.  I am certain these result are wrong, and I look forward to hearing how I can get back to a position of being able to use the scanner for real.  Thanks.

**Comment by RubenHalman** [comment]
Long story short. My suspicion is that your package manager accidentally upgraded a dependency (more specifically the dependency of the core module that performs the scan) which is not yet supported by the sfdx plugin. I applied some configuration that should prevent this from happening on your end in future versions, however, you will probably either need to reinstall the sfdx plugin or its dependencies(node modules) to resolve this. Please let me know if that helps!

**Comment by alan-birchenough** [comment]
Many thanks.  This did fix the behavioral issue, so I am now getting error reports.  Although I am still a little concerned that I am getting so many dependency warnings, I guess this can be closed.  Thanks for the quick turn-around!

Just FYI, I am including the new output from the install.

**? This plugin is not digitally signed and its authenticity cannot be verified. Continue installation?** Yes
Because you approved this plugin, you can avoid future installation confirmations by adding the plugin to the unsignedPluginAllowList.json file. For details, see https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_allowlist.htm.
Finished digital signature check.
Installing plugin lightning-flow-scanner... ⡿ [1/4] Resolving packages...
Installing plugin lightning-flow-scanner... ⣟ [1/4] Resolving packages...
warning lightning-flow-scanner > @salesforce/command@2.2.0: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
Installing plugin lightning-flow-scanner... ⣾ [1/4] Resolving packages...
warning lightning-flow-scanner > @oclif/command@1.8.36: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning lightning-flow-scanner > @salesforce/command > @oclif/command@1.8.36: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning lightning-flow-scanner > @oclif/command > @oclif/errors@1.3.6: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning lightning-flow-scanner > @salesforce/command > @oclif/parser@3.8.17: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning lightning-flow-scanner > @oclif/command > @oclif/parser@3.8.17: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
Installing plugin lightning-flow-scanner... ⣽ [1/4] Resolving packages...
warning lightning-flow-scanner > @oclif/config@1.18.17: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning lightning-flow-scanner > @oclif/command > @oclif/config@1.18.17: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning lightning-flow-scanner > @oclif/config > @oclif/errors@1.3.6: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
Installing plugin lightning-flow-scanner... ⡿ [1/4] Resolving packages...
warning lightning-flow-scanner > @salesforce/command > cli-ux@4.9.3: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
Installing plugin lightning-flow-scanner... ⣷ [1/4] Resolving packages...
Installing plugin lightning-flow-scanner... ⣾ [1/4] Resolving packages...
Installing plugin lightning-flow-scanner... ⣟ [1/4] Resolving packages...
warning lightning-flow-scanner > @oclif/command > @oclif/help@1.0.15: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning lightning-flow-scanner > @oclif/command > @oclif/help > @oclif/config@1.18.16: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning lightning-flow-scanner > @oclif/command > @oclif/help > @oclif/errors@1.3.6: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning lightning-flow-scanner > @oclif/command > @oclif/help > @oclif/config > @oclif/errors@1.3.6: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
Installing plugin lightning-flow-scanner... ⣾ [1/4] Resolving packages...
Installing plugin lightning-flow-scanner... ⢿ [1/4] Resolving packages...
Installing plugin lightning-flow-scanner... ⣻ [1/4] Resolving packages...
Installing plugin lightning-flow-scanner... ⢿ [1/4] Resolving packages...
Installing plugin lightning-flow-scanner... installed v2.13.0

**Comment by RubenHalman** [comment]
My apologies for the inconvenience. Thank you for your involvement with this project!
